version: '3.7'
services: 

  admin:
    container_name: admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-admin
    ports:
      - 80:80
    command: python3 run.py
    networks: 
      - frontend

  menu_database_api:
    container_name: menu_database_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-menu-api
    ports:
      - 4000:80
    command: python3 app.py
    networks: 
      - frontend
      - backend
      
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    build:
      context: .
      dockerfile: Dockerfile-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: menu
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks: 
      - backend
networks: 
  backend:
    name: backend
  frontend:
    name: frontend
